const cards=document.querySelectorAll(".generator-card"),generateBtn=document.getElementById("generateBtn"),copyBtn=document.getElementById("copyBtn"),result=document.getElementById("result"),generatorTitle=document.getElementById("generatorTitle"),panelIcon=document.getElementById("panelIcon"),passwordOptions=document.getElementById("passwordOptions"),usernameOptions=document.getElementById("usernameOptions"),emailOptions=document.getElementById("emailOptions"),strengthBox=document.getElementById("strengthBox"),strengthText=document.getElementById("strengthText"),strengthBar=document.getElementById("strengthBar"),passwordLength=document.getElementById("passwordLength"),lengthValue=document.getElementById("lengthValue"),themeBtn=document.getElementById("themeBtn"),navTheme=document.getElementById("navTheme"),toast=document.getElementById("toast");let currentGenerator="password";
const generatorData={password:["Password Generator","🔐"],instagram:["Instagram Username","◎"],telegram:["Telegram Username","➤"],tiktok:["TikTok Username","♪"],email:["Email Generator","✉"],freefire:["Free Fire Names","🔥"],pubg:["PUBG Names","🎮"]};
cards.forEach(card=>card.addEventListener("click",()=>{currentGenerator=card.dataset.generator;cards.forEach(c=>c.classList.remove("active"));card.classList.add("active");updatePanel(currentGenerator);generate();}));
function updatePanel(type){generatorTitle.textContent=generatorData[type][0];panelIcon.textContent=generatorData[type][1];[passwordOptions,usernameOptions,emailOptions,strengthBox].forEach(x=>x.classList.add("hidden"));if(type==="password"){passwordOptions.classList.remove("hidden");strengthBox.classList.remove("hidden")}else if(["instagram","telegram","tiktok"].includes(type))usernameOptions.classList.remove("hidden");else if(type==="email")emailOptions.classList.remove("hidden")}
passwordLength.addEventListener("input",()=>lengthValue.textContent=passwordLength.value);
function randomItem(a){return a[Math.floor(Math.random()*a.length)]}function randomNumber(min,max){return Math.floor(Math.random()*(max-min+1))+min}
function generatePassword(){let chars="";if(document.getElementById("uppercase").checked)chars+="ABCDEFGHIJKLMNOPQRSTUVWXYZ";if(document.getElementById("lowercase").checked)chars+="abcdefghijklmnopqrstuvwxyz";if(document.getElementById("numbers").checked)chars+="0123456789";if(document.getElementById("symbols").checked)chars+="!@#$%^&*()_+-=[]{}<>?";if(!chars){showToast("Select at least one option");return""}let p="";for(let i=0;i<Number(passwordLength.value);i++)p+=chars[Math.floor(Math.random()*chars.length)];return p}
function calculateStrength(p){let s=0;if(p.length>=12)s++;if(p.length>=20)s++;if(/[A-Z]/.test(p))s++;if(/[a-z]/.test(p))s++;if(/[0-9]/.test(p))s++;if(/[^A-Za-z0-9]/.test(p))s++;strengthBar.style.width=Math.min(100,Math.round(s/6*100))+"%";strengthText.textContent=s<=2?"Weak":s<=4?"Medium":s===5?"Strong":"Very Strong"}
function generateUsername(platform){let base=(document.getElementById("nameInput").value.trim()||randomItem(["pedro","dark","shadow","ghost","nova","zero","xeno","pixel","storm","phantom"])).toLowerCase().replace(/[^a-z0-9]/g,"")||"user";let style=document.getElementById("usernameStyle").value,u;if(style==="short")u=base.substring(0,Math.min(5,base.length))+randomNumber(10,99);else if(style==="clean")u=randomItem([base,"its"+base,"the"+base,base+"x"]);else if(style==="dark")u=randomItem(["dark"+base,base+"dark","x"+base,base+"void","void"+base]);else if(style==="gaming")u=randomItem([base+"gaming",base+"plays",base+"fps",base+"gg","pro"+base]);else u=randomItem([base+randomNumber(10,999),"its_"+base,base+"_x",base+".official","real"+base,base+"hub"]);return u.replace(/\./g,platform==="telegram"?"_":".").substring(0,30)}
function generateEmail(){let base=(document.getElementById("emailName").value.trim()||randomItem(["pedro","alex","nova","user","shadow","pixel","dark"])).toLowerCase().replace(/[^a-z0-9]/g,"")||"user",style=document.getElementById("emailStyle").value,n;if(style==="professional")n=base+randomNumber(10,99);else if(style==="gaming")n=base+"gaming"+randomNumber(1,99);else if(style==="numbers")n=base+randomNumber(1000,9999);else n=randomItem([base+randomNumber(10,999),"official"+base,base+"x","its"+base]);return n+"@example.com"}
const gamingNames=["亗PREDATOR亗","乂DARK乂","『PHANTOM』","么SNIPER么","⚡NOVA⚡","『GHOST』","乂SHADOW乂","亗KING亗","『ZERO』","☠DARK☠","⚔WARRIOR⚔","亗LEGEND亗","乂VENOM乂","『STORM』","么HUNTER么","⚡FURY⚡","亗REAPER亗","『VIPER』","乂PHOENIX乂","☠NIGHT☠"];
function generate(){let output="";if(currentGenerator==="password"){output=generatePassword();if(output){result.textContent=output;calculateStrength(output)}}else if(["instagram","telegram","tiktok"].includes(currentGenerator))result.textContent=generateUsername(currentGenerator);else if(currentGenerator==="email")result.textContent=generateEmail();else result.textContent=randomItem(gamingNames);result.animate([{opacity:0,transform:"translateY(5px)"},{opacity:1,transform:"translateY(0)"}],{duration:220,easing:"ease-out"})}
generateBtn.addEventListener("click",generate);
copyBtn.addEventListener("click",async()=>{let text=result.textContent.trim();if(!text||text==="Click Generate"){showToast("Nothing to copy");return}try{await navigator.clipboard.writeText(text);showToast("Copied ✓")}catch{showToast("Copy failed")}});
function showToast(m){toast.textContent=m;toast.classList.add("show");setTimeout(()=>toast.classList.remove("show"),1800)}
function toggleTheme(){document.body.classList.toggle("light");themeBtn.textContent=document.body.classList.contains("light")?"☾":"☼"}
themeBtn.addEventListener("click",toggleTheme);navTheme.addEventListener("click",toggleTheme);
document.querySelectorAll(".nav-item[data-scroll]").forEach(item=>item.addEventListener("click",()=>{document.querySelector(item.dataset.scroll==="generator"?".generator-panel":"main").scrollIntoView({behavior:"smooth"})}));
generate();